services:
  automaton-bot:
    build: .
    env_file:
      - .env
    container_name: automaton-bot
    volumes:
      - .:/usr/src/automaton-bot-discord
    working_dir: /usr/src/automaton-bot-discord
    restart: always
    command: ["python", "./main.py"]